name: 'Invalidate AWS CloudFront Distribution'
description: 'Invalidate AWS CloudFront Distribution'
author: 'Rick Meneely <rick@devopspolis.com>'
branding:
  icon: cloud-rain
  color: purple

inputs:
  distribution-id:
    description: CloudFront Distribution ID
    type: string
    required: true
  paths:
    description: CloudFront Invalidation Paths
    type: string
    required: false
    default: '/*'
  role:
    description: AWS role to assume
    type: string
    required: false
  aws-region:
    description: AWS region
    type: string
    required: false

outputs:
  invalidation-id:
    description: The Invalidation ID
    value: ${{ steps.invalidate.outputs.invalidation_id }}

runs:
  using: composite
  steps:
    - name: Set AWS_REGION
      if: ${{ inputs.role }}
      shell: bash
      run: |
        if [[ -n "${{ inputs.aws-region }}" ]]; then
          echo "AWS_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV
        elif [[ -z "${AWS_REGION}" ]]; then
          echo "❌ aws-region input or AWS_REGION environment variable is required if specifying role"
          exit 1
        fi

    - name: Resolve role ARN if short name
      if: ${{ inputs.role }}
      id: resolve-role
      shell: bash
      run: |
        role="${{ inputs.role }}"
        if [[ "$role" != arn:aws:iam::* ]]; then
          echo "Resolving short role name to full ARN..."
          # For OIDC, we need the AWS_ACCOUNT_ID to be available
          if [[ -z "$AWS_ACCOUNT_ID" ]]; then
            echo "❌ AWS_ACCOUNT_ID environment variable is required when using short role names"
            exit 1
          fi
          role="arn:aws:iam::${AWS_ACCOUNT_ID}:role/$role"
        fi
        echo "role_arn=$role" >> $GITHUB_OUTPUT
        echo "✅ Using role: $role"

    - name: Configure AWS credentials (if role specified)
      if: ${{ inputs.role }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.resolve-role.outputs.role_arn }}
        role-session-name: GitHubActionDeploySession
        aws-region: ${{ env.AWS_REGION }}

    - name: Invalidate CloudFront Distribution
      id: invalidate
      shell: bash
      run: |
        echo "Requesting CloudFront invalidation for distribution ${{ inputs.distribution-id }} and paths '${{ inputs.paths }}'..."
        invalidation_output=$(aws cloudfront create-invalidation \
          --distribution-id "${{ inputs.distribution-id }}" \
          --paths "${{ inputs.paths }}")

        echo "$invalidation_output"
        invalidation_id=$(echo "$invalidation_output" | jq -r '.Invalidation.Id')
        echo "invalidation_id=$invalidation_id" >> "$GITHUB_OUTPUT"
