name: 'Invalidate AWS CloudFront Distribution'
description: 'Invalidate AWS CloudFront Distribution'
author: 'Rick Meneely <rick@devopspolis.com>'
branding:
  icon: cloud-rain
  color: purple

inputs:
  distribution-id:
    description: CloudFront Distribution ID
    type: string
    required: true
  paths:
    description: CloudFront Invalidation Paths
    type: string
    required: false
    default: '/*'

outputs:
  invalidation-id:
    description: The Invalidation ID
    value: ${{ steps.invalidate.outputs.invalidation_id }}

runs:
  using: composite
  steps:
    - name: Invalidate CloudFront Distribution
      id: invalidate
      shell: bash
      run: |
        echo "Requesting CloudFront invalidation for distribution ${{ inputs.distribution-id }} and paths '${{ inputs.paths }}'..."
        invalidation_output=$(aws cloudfront create-invalidation \
          --distribution-id "${{ inputs.distribution-id }}" \
          --paths "${{ inputs.paths }}")

        echo "$invalidation_output"
        invalidation_id=$(echo "$invalidation_output" | jq -r '.Invalidation.Id')
        echo "invalidation_id=$invalidation_id" >> "$GITHUB_OUTPUT"
