name: 'Invalidate AWS CloudFront Distribution'
description: 'Invalidate AWS CloudFront Distribution'
author: 'Rick Meneely <rick@devopspolis.com>'
branding:
  icon: cloud-rain
  color: purple

inputs:
  distribution-id:
    description: CloudFront Distribution ID
    type: string
    required: true
  paths:
    description: CloudFront Invalidation Paths
    type: string
    required: false
    default: '/*'
  role:
    description: AWS role to assume
    type: string
    required: false

outputs:
  invalidation-id:
    description: The Invalidation ID
    value: ${{ steps.invalidate.outputs.invalidation_id }}

runs:
  using: composite
  steps:
    - name: Resolve role ARN if short name
      if: inputs.role
      id: resolve-role
      shell: bash
      run: |
        role="${{ inputs.role }}"
        if [[ "$role" != arn:aws:iam::* ]]; then
          echo "Resolving short role name to full ARN..."
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          role="arn:aws:iam::$ACCOUNT_ID:role/$role"
        fi
        echo "role_arn=$role" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      if: ${{ inputs.role }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ steps.resolve-role.outputs.role_arn }}
        role-session-name: GitHubActionDeploySession

    - name: Invalidate CloudFront Distribution
      id: invalidate
      shell: bash
      run: |
        echo "Requesting CloudFront invalidation for distribution ${{ inputs.distribution-id }} and paths '${{ inputs.paths }}'..."
        invalidation_output=$(aws cloudfront create-invalidation \
          --distribution-id "${{ inputs.distribution-id }}" \
          --paths "${{ inputs.paths }}")

        echo "$invalidation_output"
        invalidation_id=$(echo "$invalidation_output" | jq -r '.Invalidation.Id')
        echo "invalidation_id=$invalidation_id" >> "$GITHUB_OUTPUT"
